# Generated by Django 5.2 on 2025-11-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='contact_info',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='created_at',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='patient',
            name='anonymized_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='anonymized_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
